### ISSUE TITLE
there is no description of scenarios

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#140]
In order to ease the analysis of scenarios, an overview regarding most important assumptions and parameters of each scenario would be helpful. Here's my list key parameters I would like to have included

- land-use restrictions
- pth storage size/number
- battery storage scenario
- generation capacity scenario
- energy efficiency

It might make sense to split the table. For example, it could be helpful to create a separate table for "generation capacity scenarios" which repeat in multiple scenarios. We can decide on that later. First, I would like to collect important information that should be contained in the description of scenarios.

**Comment by nesnoj** [comment]
Related: #64

**Comment by gplssm** [comment]
|Key scenario parameters | Values | Explanation |
|------------------------------------|-----------|-----------------|
| Generation capacity | NEP2035/ISE2050 | Study where generation capacity data is taken from with link to table explaining these scenarios |
| Land-use restrictions | RE/PV/Wind-, RE/PV/Wind, RE/PV/Wind+ | Acronym of land-use restrictions with link to table detailing about available area (ha + %) for PV and Wind and resulting max. possible capacity |
| Demand-side management | DSM-,DSM,DSM+ | market penetration in % of households |
| Battery storage |  BAT-, BAT, BAT+| battery scenario, would involve two number (large/small)
| PTH th. storage| PTH-,PTH,PTH+ | % of household with HP being equipped with an additional heat storage, explain separately that also size of storage varies, one number (only decentral HP are additionally equipped with head storages) |
| Autarky | AUT0/"", AUT80, AUT90 | lower limit for autark supply with ABW |


One question remains: either we only use acronyms in the above table and link to a separate table for each parameter that explains the details. Or we directly include the number in MW, ha, % or whatever. Opinions?
Further idea: whereever possible, the numbers are filled in. Below the table we can than explain in one subsection for each scenario feature what it means in details (i.e. 80 % AUT is 80 % autarky on annual balance).

**Comment by nesnoj** [comment]
Notes on current implementation:
- If a flex is not contained in the scenario's name, it's not contained in the scenario at all (like AUT row in your table), e.g. "NEP" indicates NEP with no flex (as we wanted to avoid to mention the non-existence). We also could use something like "_noflex" but for scenarios like "NEP_RE-_DSM" it's not clear if there's BAT included or not. I'd stick to the do-not-mention-if-not-contained way.
- We do not have LOW level flex indicated by "-", example for DSM:
  - ""=no
  - "DSM"=med
  - "DSM+"=high
- We agreed on 4 different levels of PV+Wind which are currently reflected in the names as follows:
  - "RE-"=legal SQ
  - ""=NEP numbers
  - "Wind+"/"PV+"=somewhat realistic value between "" and "RE++"
  - "RE++"= crazy max **(needs to be added to table)**

Do you agree on this notation?
If so, I'd or you can alter the table above..

**Comment by gplssm** [comment]
> Notes on current implementation:
> 
>     * If a flex is not contained in the scenario's name, it's not contained in the scenario at all (like AUT row in your table), e.g. "NEP" indicates NEP with no flex (as we wanted to avoid to mention the non-existence). We also could use something like "_noflex" but for scenarios like "NEP_RE-_DSM" it's not clear if there's BAT included or not. I'd stick to the do-not-mention-if-not-contained way.
> 
>     * We do not have LOW level flex indicated by "-", example for DSM:
>       
>       * ""=no
>       * "DSM"=med
>       * "DSM+"=high
> 
>     * We agreed on 4 different levels of PV+Wind which are currently reflected in the names as follows:
>       
>       * "RE-"=legal SQ
>       * ""=NEP numbers
>       * "Wind+"/"PV+"=somewhat realistic value between "" and "RE++"
>       * "RE++"= crazy max **(needs to be added to table)**
> 
> 
> Do you agree on this notation?
> If so, I'd or you can alter the table above..

Yes! Let's stick do-not-mention-if-not-contained (as discussed yesterday).

In particular, if we take this into account

> One question remains: either we only use acronyms in the above table and link to a separate table for each parameter that explains the details. Or we directly include the number in MW, ha, % or whatever. Opinions?
Further idea: whereever possible, the numbers are filled in. Below the table we can than explain in one subsection for each scenario feature what it means in details (i.e. 80 % AUT is 80 % autarky on annual balance).

we can kept not included things unmentioned and fill in concrete numbers like 0 % for DSM.

Let's use examples

| Scenario | Generation capacity | Land-use restrictions | Demand-side management | Battery storage | PTH th. storage | Autarky|
|------------- |----------------------------|------------------------------|--------------------------------------|----------------------|----------------------|--------------|
| NEP | NEP | RE- | 0 | 0 | 20 | 0 | 

That's what the mentioned NEP scenario looks like.

Sure, we have add

- one line with units
- split some of the cols
  - Land-use: PV and wind
  - maybe also generation capacity, if we don't want to use a reference to another table

**Comment by gplssm** [comment]
### TODOs

- [ ] extract relevant data from `scenarios.csv`
- [ ] (optional) re-format column headers to span across multiple columns
- [ ] Include in docs
- [ ] translate generation capacity columns to meaningful values

**Comment by nesnoj** [comment]
For the last task you may wanna make use of the recent overview in scn ods 0d as lookup table..

**Comment by nesnoj** [comment]
Hey @gplssm, I added a lookup table for the RE scenarios in e00b25a for the matching.
Alternatively, it might be worth to just simply create a 2nd `scenarios.csv` table from `scenarios.csv` and the new file instead of match it in your [display function](https://github.com/windnode/WindNODE_ABW/blob/e00b25a4e1318d6251ef8e788d99aac45e44dd43/docs/conf.py#L47)...

PS: Please add `pv_roof_installed_power` to the scenario table too.

**Comment by gplssm** [comment]
Thanks! That helped :) I added `pv_roof_installed_power` as well.

While completing the detailed description of scenario dimensions, I stumbled upon some knowledge gaps. Maybe you can help me

**RE**

@nesnoj could you please add information on how PV installable capacity is restricied [here](https://github.com/windnode/WindNODE_ABW/blob/d33126b29e4698cecd42a134751f2bd162ceea95/docs/_data/re_scenarios_nep.csv#L4-L6) (WIND+, PV+, RE++) and [here](https://raw.githubusercontent.com/windnode/WindNODE_ABW/d33126b29e4698cecd42a134751f2bd162ceea95/docs/_data/re_scenarios_ise.csv#L4) (RE++)?

**PTH**

- PTH scenarios currently only describe thermal storage capacity in dec./cen. heating systems. I would like to talk about installed HP capacity as well. Where can information about it?
- How is the additional storage capacity for decentral heating system being calculated?
- How is the additional storage capacity for district heating system being calculated?

**Comment by nesnoj** [comment]
> @nesnoj could you please add information on how PV installable capacity is restricied

I reworked the tables in 506e70e9ae989afe071110a983132c021d62b1d5 by listing the restrictions individually. R u ok with that?

>     * PTH scenarios currently only describe thermal storage capacity in dec./cen. heating systems. I would like to talk about installed HP capacity as well. Where can information about it?

Cf. odt on methods.

>     * How is the additional storage capacity for decentral heating system being calculated?

Cf. odt on methods (results see sec 2.6.2 and 2020-06-24_Szenarien_Ergebnisse_Prognosen_2050.ods)

>     * How is the additional storage capacity for district heating system being calculated?

Cf. odt on methods (sec 2.6.3)

If that's not self-explaining, please get back to me.

**Comment by nesnoj** [comment]
Uh, I screwed the CSVs using colon instead of comma as separator before.
Fixed.

One more thing: The desaggregation from ISE/NEP to region is not describet, might be helpful to drop some notes on this. I inserted a placeholder in `scenarios.rst`
